### ISSUE TITLE
Buy STM32 Dev Kit

### ISSUE THREAD

**Issue by ppapadeas** [librespacefoundation/upsat-obc-software#2]
Need to know which one @mashua ?

**Comment by mashua** [comment]
dev boards like this ( http://www.ebay.com/itm/STM32F4-DISCOVERY-USB-STM32F407VGT6-STM32-ARM-Cortex-M4-Development-Board-/172055710388?hash=item280f51cab4:g:o7oAAOSwZVhWTXVa ) will suffice, apparently only for dev purposes...
