### ISSUE TITLE
Check differences between stm32f405 and stm32f407

### ISSUE THREAD

**Issue by nchronas** [librespacefoundation/upsat-obc-software#6]
Check differences between stm32f405 mcu used in the OBC board and stm32f407 used in the discovery kits.

**Comment by mashua** [comment]
from st's site (http://www.st.com/web/catalog/mmc/FM141/SC1169/SS1577) comparing the STM32F405RG and STM32F407VG i have found differences only on pacakaging and plus that the 07 supports ethernet and has more IOs.
Flash size, RAM memory, speed, number of usart/uart, i2s, i2c, spi interfaces are the same.
